; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps =
	olikraus/U8g2@^2.35.19
lib_extra_dirs = 
	$PROJECT_DIR/lib/uEEPROMlib-master

[env:handset-f303cc]
platform = ststm32
board = robotdyn_blackpill_f303cc
framework = arduino
upload_protocol = stlink
build_src_flags = 
	-include include/boards/handset-f303cc/board.h
	-D MIXERS_FILE=\"boards/handset-f303cc/mixers.c\"
	
monitor_dtr = 1
monitor_speed = 115200

[env:pistol-grip-f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
build_src_flags = 
	-include include/boards/pistol-grip-f103c8/board.h
	-D MIXERS_FILE=\"boards/pistol-grip-f103c8/mixers.c\"
monitor_dtr = 1